# Generated by Django 5.2.18 on 2026-10-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=200, verbose_name='SMTP server')),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='587 for TLS, 465 for SSL.', verbose_name='SMTP port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('smtp_username', models.CharField(blank=True, max_length=200, verbose_name='Email login (username)')),
                ('smtp_password', models.CharField(blank=True, help_text='For Gmail, create an "App Password" in your Google account security settings.', max_length=200, verbose_name='Email password / App password')),
                ('from_email', models.EmailField(blank=True, help_text='Usually the same as the email login.', max_length=254, verbose_name='Send emails from')),
                ('notify_email', models.EmailField(blank=True, help_text='Quote / contact form enquiries are delivered to this address.', max_length=254, verbose_name='Send enquiries to')),
            ],
            options={
                'verbose_name': 'Email (SMTP) Settings',
                'verbose_name_plural': 'Email (SMTP) Settings',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Interior • Exterior • Commercial', max_length=150, verbose_name='Small text above heading')),
                ('heading', models.CharField(default='Crafting Spaces That Feel Like Home', max_length=200, verbose_name='Main heading')),
                ('description', models.TextField(default='From bespoke kitchens and wardrobes to striking facades and commercial fit-outs — we design and build every detail, end to end.', verbose_name='Description')),
                ('background_image', models.ImageField(blank=True, help_text='Large landscape photo (at least 1920px wide recommended).', null=True, upload_to='hero/', verbose_name='Background image')),
                ('primary_button_text', models.CharField(default='Explore Our Work', help_text='Scrolls down to the Interior section.', max_length=50, verbose_name='Main button text')),
                ('secondary_button_text', models.CharField(default='Get a Quote', help_text='Scrolls down to the Contact section.', max_length=50, verbose_name='Second button text')),
            ],
            options={
                'verbose_name': 'Hero Banner (Top Section)',
                'verbose_name_plural': 'Hero Banner (Top Section)',
            },
        ),
        migrations.CreateModel(
            name='NavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('label', models.CharField(max_length=50, verbose_name='Menu text')),
                ('section', models.CharField(choices=[('home', 'Home (top of page)'), ('interior', 'Interior section'), ('exterior', 'Exterior section'), ('projects', 'Projects section'), ('about', 'About section'), ('contact', 'Contact section')], help_text='Which part of the page this link scrolls to.', max_length=30, verbose_name='Scrolls to')),
            ],
            options={
                'verbose_name': 'Navbar Menu Link',
                'verbose_name_plural': 'Navbar Menu Links',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Classic Comfort Interior and Exterior', max_length=150, verbose_name='Company name')),
                ('logo', models.ImageField(blank=True, help_text='Shown in the navbar and also used as the browser tab icon (favicon). A square image works best.', null=True, upload_to='site/', verbose_name='Logo')),
                ('nav_button_text', models.CharField(default='Get a Quote', help_text='The button on the right of the navbar. It scrolls to the Contact section.', max_length=50, verbose_name='Navbar button text')),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
