# Generated by Django 5.2.18 on 2026-10-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_search_engines',
            field=models.BooleanField(default=True, help_text='Untick only while the site is under construction.', verbose_name='Allow Google to show this website'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Full live address of the website, e.g. https://www.classiccomfort.in', verbose_name='Website address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='e.g. G-XXXXXXXXXX', max_length=30, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='Only the content value from the google-site-verification meta tag.', max_length=100, verbose_name='Google Search Console code'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_author',
            field=models.CharField(blank=True, default='Classic Comfort Interior and Exterior', max_length=100, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(default='From bespoke kitchens and wardrobes to striking facades and commercial fit-outs, Classic Comfort designs and builds every detail, end to end.', help_text='The short summary under the link in Google. Keep under 155–160 characters.', max_length=170, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, default='interior design, exterior design, commercial interiors, modular kitchen, wardrobes, facade design, home renovation', help_text='Comma separated words people might search for.', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(default='Classic Comfort Interior and Exterior | Interior, Exterior & Commercial Design', help_text='Shown in the browser tab and as the blue link in Google. Keep under 60–70 characters.', max_length=100, verbose_name='Page title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_description',
            field=models.CharField(blank=True, help_text='Leave blank to use the meta description.', max_length=200, verbose_name='Share description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Preview image when the link is shared. 1200 × 630 px recommended. Leave blank to use the hero background.', null=True, upload_to='site/', verbose_name='Share image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title shown when the link is shared. Leave blank to use the page title.', max_length=100, verbose_name='Share title'),
        ),
    ]
