# Generated by Django 5.2.18 on 2026-10-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_site_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='About Us', max_length=50, verbose_name='Small heading')),
                ('intro', models.CharField(blank=True, help_text='Wrap words in *stars* to show them in gold, or in _underscores_ for italic. Leave an empty line between paragraphs.', max_length=255, verbose_name='Opening line')),
                ('content', models.TextField(blank=True, help_text='Wrap words in *stars* to show them in gold, or in _underscores_ for italic. Leave an empty line between paragraphs.', verbose_name='Main text')),
                ('closing_text', models.TextField(blank=True, help_text='Wrap words in *stars* to show them in gold, or in _underscores_ for italic. Leave an empty line between paragraphs.', verbose_name='Closing lines')),
                ('image', models.ImageField(blank=True, help_text='Tall portrait photo works best (about 3:4).', null=True, upload_to='about/', verbose_name='Side image')),
                ('vision_title', models.CharField(default='Our Vision', max_length=100, verbose_name='Vision heading')),
                ('vision_text', models.CharField(blank=True, help_text='Wrap words in *stars* to show them in gold, or in _underscores_ for italic. Leave an empty line between paragraphs.', max_length=255, verbose_name='Vision text')),
                ('promise_title', models.CharField(default='Our Promise', max_length=100, verbose_name='Promise heading')),
            ],
            options={
                'verbose_name': 'About Us Section',
                'verbose_name_plural': 'About Us Section',
            },
        ),
        migrations.AlterField(
            model_name='navmenuitem',
            name='section',
            field=models.CharField(choices=[('home', 'Home (top of page)'), ('about', 'About section'), ('interior', 'Interior section'), ('exterior', 'Exterior section'), ('projects', 'Projects section'), ('contact', 'Contact section')], help_text='Which part of the page this link scrolls to.', max_length=30, verbose_name='Scrolls to'),
        ),
        migrations.CreateModel(
            name='AboutPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('text', models.CharField(max_length=60, verbose_name='Promise')),
                ('about', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='core.aboutsection')),
            ],
            options={
                'verbose_name': 'Promise',
                'verbose_name_plural': 'Our Promise words',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(default='Works', max_length=50, verbose_name='Small text below')),
                ('section', models.CharField(blank=True, choices=[('home', 'Home (top of page)'), ('about', 'About section'), ('interior', 'Interior section'), ('exterior', 'Exterior section'), ('projects', 'Projects section'), ('contact', 'Contact section')], help_text='Optional: clicking it scrolls to this section.', max_length=30, verbose_name='Scrolls to')),
                ('about', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='core.aboutsection')),
            ],
            options={
                'verbose_name': 'Work type',
                'verbose_name_plural': 'Work types (Interior / Exterior / Commercial row)',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
