# Generated by Django 5.2.18 on 2026-10-08 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(max_length=60, verbose_name='Small heading')),
                ('heading', models.CharField(max_length=100, verbose_name='Main heading')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('enquire_button_text', models.CharField(default='Enquire', help_text='Shown on every card. Clicking it scrolls to the Contact section.', max_length=30, verbose_name='Card button text')),
            ],
            options={
                'verbose_name': 'Interior Works Section',
                'verbose_name_plural': 'Interior Works Section',
            },
        ),
        migrations.CreateModel(
            name='InteriorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Short description')),
                ('image', models.ImageField(blank=True, help_text='Landscape photo (about 4:3).', null=True, upload_to='services/', verbose_name='Image')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.interiorsection')),
            ],
            options={
                'verbose_name': 'Interior service card',
                'verbose_name_plural': 'Interior service cards',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
