# Generated by Django 5.2.18 on 2026-10-08 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_interior_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='Showcase', max_length=60, verbose_name='Small heading')),
                ('heading', models.CharField(max_length=100, verbose_name='Main heading')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Interior Projects Gallery',
                'verbose_name_plural': 'Interior Projects Gallery',
            },
        ),
        migrations.CreateModel(
            name='InteriorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('title', models.CharField(max_length=80, verbose_name='Room / project name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image')),
                ('size', models.CharField(choices=[('normal', 'Normal (1 box)'), ('wide', 'Wide (2 boxes across)'), ('tall', 'Tall (2 boxes down)')], default='normal', help_text='Controls the shape of the photo in the gallery grid. The number (01, 02…) is added automatically from the display order.', max_length=10, verbose_name='Tile size')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.interiorprojectsection')),
            ],
            options={
                'verbose_name': 'Interior project photo',
                'verbose_name_plural': 'Interior project photos',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
