# Generated by Django 5.2.18 on 2026-10-08 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exterior_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(max_length=60, verbose_name='Small heading')),
                ('heading', models.CharField(max_length=150, verbose_name='Main heading')),
            ],
            options={
                'verbose_name': 'Our Process Section',
                'verbose_name_plural': 'Our Process Section',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(max_length=60, verbose_name='Small heading')),
                ('heading', models.CharField(max_length=150, verbose_name='Main heading')),
            ],
            options={
                'verbose_name': 'Why Choose Us Section',
                'verbose_name_plural': 'Why Choose Us Section',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('description', models.CharField(help_text='The number (01, 02…) is added automatically from the display order.', max_length=255, verbose_name='Description')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.processsection')),
            ],
            options={
                'verbose_name': 'Process step',
                'verbose_name_plural': 'Process steps',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhyChooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('description', models.CharField(help_text='The number (01, 02…) is added automatically from the display order.', max_length=255, verbose_name='Description')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.whychoosesection')),
            ],
            options={
                'verbose_name': 'Reason',
                'verbose_name_plural': 'Reasons (numbered cards)',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
