# Generated by Django 5.2.18 on 2026-10-08 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_why_choose_and_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('title', models.CharField(max_length=100, verbose_name='Project name')),
                ('subtitle', models.CharField(blank=True, default='Residential', help_text='e.g. Residential, Office, Retail', max_length=60, verbose_name='Project type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Cover image')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Our Projects — project list',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='Portfolio', max_length=60, verbose_name='Small heading')),
                ('heading', models.CharField(default='Our Projects', max_length=100, verbose_name='Main heading')),
                ('all_filter_text', models.CharField(default='All', max_length=30, verbose_name='"All" button text')),
            ],
            options={
                'verbose_name': 'Our Projects Section',
                'verbose_name_plural': 'Our Projects Section',
            },
        ),
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='Testimonials', max_length=60, verbose_name='Small heading')),
                ('heading', models.CharField(default='Words from our clients', max_length=100, verbose_name='Main heading')),
            ],
            options={
                'verbose_name': 'Testimonials Section',
                'verbose_name_plural': 'Testimonials Section',
            },
        ),
        migrations.CreateModel(
            name='PortfolioProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('image', models.ImageField(upload_to='portfolio/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Caption')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.portfolioproject')),
            ],
            options={
                'verbose_name': 'Extra photo',
                'verbose_name_plural': 'Extra photos (opened when the arrow is clicked)',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('name', models.CharField(help_text='Shown as a filter button and as the small label on each project.', max_length=50, verbose_name='Category name')),
                ('slug', models.SlugField(editable=False, max_length=60, unique=True)),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.portfoliosection')),
            ],
            options={
                'verbose_name': 'Filter category',
                'verbose_name_plural': 'Filter categories (buttons)',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.projectcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('quote', models.TextField(help_text='Quotation marks are added automatically.', verbose_name='Client review')),
                ('client_name', models.CharField(help_text='e.g. Homeowner, Business Owner, or the client’s name.', max_length=80, verbose_name='Client name / role')),
                ('project_type', models.CharField(blank=True, help_text='e.g. Kitchen & Wardrobes', max_length=80, verbose_name='Work done')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.testimonialsection')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
