# Generated by Django 5.2.18 on 2026-10-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_portfolio_and_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='Start Today', max_length=60, verbose_name='Small heading')),
                ('heading', models.CharField(default='Let’s Create A Space You’ll Love', max_length=150, verbose_name='Main heading')),
                ('background_image', models.ImageField(blank=True, help_text='Wide landscape photo (at least 1920px wide). A dark overlay is added automatically.', null=True, upload_to='cta/', verbose_name='Background image')),
                ('primary_button_text', models.CharField(default='Get a Quote', help_text='Scrolls to the Contact section.', max_length=50, verbose_name='Main button text')),
                ('secondary_button_text', models.CharField(default='Contact Us', help_text='Scrolls to the Contact section.', max_length=50, verbose_name='Second button text')),
            ],
            options={
                'verbose_name': 'Start Today Banner',
                'verbose_name_plural': 'Start Today Banner',
            },
        ),
    ]
