# Generated by Django 5.2.18 on 2026-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cta_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='Contact', max_length=60, verbose_name='Small heading')),
                ('heading', models.CharField(default='Tell us about your space', max_length=150, verbose_name='Main heading')),
                ('description', models.CharField(default='Share a few details and our team will get back within one working day.', max_length=255, verbose_name='Description')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone_numbers', models.CharField(blank=True, help_text='Separate multiple numbers with a comma. Each one becomes a tap-to-call link.', max_length=100, verbose_name='Phone numbers')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('instagram_handle', models.CharField(blank=True, help_text='Without the @, e.g. classic_Comfort_interior', max_length=60, verbose_name='Instagram username')),
                ('form_button_text', models.CharField(default='Send Enquiry', max_length=40, verbose_name='Form button text')),
                ('service_placeholder', models.CharField(default='Service Required', max_length=60, verbose_name='Service dropdown text')),
                ('success_message', models.CharField(default='Thank you! Our team will get back to you within one working day.', max_length=255, verbose_name='Message after sending')),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('service', models.CharField(max_length=120, verbose_name='Service required')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=12, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Only visible in the admin.', verbose_name='Internal notes')),
                ('email_sent', models.BooleanField(default=False, editable=False, verbose_name='Email notification sent')),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received on')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries (from contact form)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='auto_reply_message',
            field=models.TextField(default='Thank you for reaching out to us. We have received your enquiry and our team will get back to you within one working day.\n\nWarm regards,\nClassic Comfort Interior and Exterior', help_text='"Hi <name>," is added at the top and a summary of their enquiry at the bottom.', verbose_name='Confirmation email message'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='auto_reply_subject',
            field=models.CharField(default='Thank you for contacting Classic Comfort Interior and Exterior', max_length=150, verbose_name='Confirmation email subject'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='send_auto_reply',
            field=models.BooleanField(default=True, help_text='After a form is submitted, the customer receives a thank-you email.', verbose_name='Send confirmation email to the customer'),
        ),
    ]
