# Generated by Django 5.2.18 on 2026-10-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contact_and_enquiries'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_logo', models.ImageField(blank=True, help_text='Optional light version of the logo for the dark footer. Leave blank to use the main logo from Website Settings.', null=True, upload_to='site/', verbose_name='Footer logo')),
                ('about_text', models.CharField(default='Interior, exterior and commercial works — designed and built with care.', max_length=255, verbose_name='Short description')),
                ('follow_text', models.CharField(default='Follow us,', max_length=60, verbose_name='Social media heading')),
                ('quick_links_title', models.CharField(default='Quick Links', help_text='Links come from "Navbar Menu Links".', max_length=40, verbose_name='Column 1 heading')),
                ('interior_title', models.CharField(default='Interior', help_text='Links come from the Interior service cards.', max_length=40, verbose_name='Column 2 heading')),
                ('exterior_title', models.CharField(default='Exterior', help_text='Links come from the Exterior service cards.', max_length=40, verbose_name='Column 3 heading')),
                ('contact_title', models.CharField(default='Contact', help_text='Address, phone and email come from "Contact Section".', max_length=40, verbose_name='Column 4 heading')),
                ('copyright_text', models.CharField(default='All rights reserved.', help_text='Shown as: © <current year> <company name>. <this text>', max_length=150, verbose_name='Copyright text')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('x', 'X (Twitter)'), ('pinterest', 'Pinterest')], max_length=20, verbose_name='Platform')),
                ('url', models.URLField(blank=True, help_text='Full link to the page. Icons without a link are hidden on the website.', verbose_name='Page link')),
                ('footer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.footersettings')),
            ],
            options={
                'verbose_name': 'Social media link',
                'verbose_name_plural': 'Social media links',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
