# Generated by Django 5.2.18 on 2026-10-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_call', models.BooleanField(default=True, verbose_name='Show call button')),
                ('call_number', models.CharField(default='6374851724', help_text='10-digit mobile number. +91 is added automatically.', max_length=20, verbose_name='Call number')),
                ('show_whatsapp', models.BooleanField(default=True, verbose_name='Show WhatsApp button')),
                ('whatsapp_number', models.CharField(default='6374851724', help_text='10-digit mobile number. +91 is added automatically.', max_length=20, verbose_name='WhatsApp number')),
                ('whatsapp_message', models.CharField(blank=True, default='Hi, I would like to know more about your interior and exterior services.', help_text='Pre-filled text when the chat opens. Leave blank for an empty chat.', max_length=200, verbose_name='WhatsApp starting message')),
                ('show_email', models.BooleanField(default=True, verbose_name='Show email button')),
                ('email', models.EmailField(default='classiccomfortinteriorexterior@gmail.com', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Floating Contact Buttons',
                'verbose_name_plural': 'Floating Contact Buttons',
            },
        ),
        migrations.AddField(
            model_name='footersettings',
            name='credit_name',
            field=models.CharField(default='Vetri IT Systems', max_length=80, verbose_name='Developer name'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='credit_prefix',
            field=models.CharField(default='Designed & Developed by', max_length=80, verbose_name='Credit text'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='credit_url',
            field=models.URLField(default='https://vetriitsystems.com/', help_text='The developer name links here (opens in a new tab).', verbose_name='Developer website'),
        ),
    ]
