# Generated by Django 5.2.18 on 2026-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_footer_credit_floating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floatingbuttons',
            name='email',
        ),
        migrations.RemoveField(
            model_name='floatingbuttons',
            name='show_email',
        ),
        migrations.AddField(
            model_name='floatingbuttons',
            name='instagram_url',
            field=models.URLField(default='https://www.instagram.com/classic_Comfort_interior/', verbose_name='Instagram page link'),
        ),
        migrations.AddField(
            model_name='floatingbuttons',
            name='show_instagram',
            field=models.BooleanField(default=True, verbose_name='Show Instagram button'),
        ),
    ]
