# Generated by Django 5.2.18 on 2026-10-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_floating_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(default='Planning a new home or revamping an office? Our interior design services cover everything from a modular kitchen to a full commercial fit-out, with one team handling design, work and finishing.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='primary_button_text',
            field=models.CharField(default='View Interior Works', help_text='Scrolls down to the Interior section.', max_length=50, verbose_name='Main button text'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondary_button_text',
            field=models.CharField(default='Request a Quote', help_text='Scrolls down to the Contact section.', max_length=50, verbose_name='Second button text'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='tagline',
            field=models.CharField(default='Interior · Exterior · Commercial', max_length=150, verbose_name='Small text above heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(default='Classic Comfort Interior & Exterior offers interior design services, modular kitchens, wardrobes, false ceilings and facade works. Get a quote today.', help_text='The short summary under the link in Google. Keep under 155–160 characters.', max_length=170, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(default='Interior Designers in Chennai | Classic Comfort Interior', help_text='Shown in the browser tab and as the blue link in Google. Keep under 60–70 characters.', max_length=100, verbose_name='Page title'),
        ),
    ]
