# Generated by Django 5.2.18 on 2026-10-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seo_meta_and_hero_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='heading',
            field=models.CharField(blank=True, help_text='The large heading of the section (H2 for Google).', max_length=150, verbose_name='Main heading'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_text',
            field=models.TextField(blank=True, help_text='Wrap words in *stars* to show them in gold, or in _underscores_ for italic. Leave an empty line between paragraphs.', verbose_name='Mission text'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_title',
            field=models.CharField(default='Our Mission', max_length=100, verbose_name='Mission heading'),
        ),
    ]
