# Generated by Django 5.2.18 on 2026-10-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_about_heading_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosection',
            name='all_filter_title',
            field=models.CharField(blank=True, help_text='Shown when the mouse rests on the button (also read by Google).', max_length=120, verbose_name='"All" button hover text'),
        ),
        migrations.AddField(
            model_name='portfoliosection',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Intro text'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='hover_title',
            field=models.CharField(blank=True, help_text='Shown when the mouse rests on the button (also read by Google).', max_length=120, verbose_name='Button hover text'),
        ),
    ]
