# Generated by Django 5.2.18 on 2026-10-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_portfolio_intro_hover_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='One-line description'),
        ),
    ]
