# Generated by Django 5.2.18 on 2026-10-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_portfolio_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctasection',
            name='description',
            field=models.TextField(blank=True, help_text='Leave an empty line between paragraphs.', verbose_name='Text below heading'),
        ),
        migrations.AddField(
            model_name='testimonialsection',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Intro text'),
        ),
    ]
