# Generated by Django 5.2.18 on 2026-10-09 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_testimonial_cta_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='FAQ', max_length=60, verbose_name='Small heading')),
                ('heading', models.CharField(default='Frequently Asked Questions', max_length=150, verbose_name='Main heading')),
            ],
            options={
                'verbose_name': 'FAQ Section',
                'verbose_name_plural': 'FAQ Section',
            },
        ),
        migrations.AddField(
            model_name='contactsection',
            name='email_placeholder',
            field=models.CharField(default='Email', max_length=60, verbose_name='Email field text'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='intro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Intro text'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='message_placeholder',
            field=models.CharField(default='Message', max_length=120, verbose_name='Message field text'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='name_placeholder',
            field=models.CharField(default='Name', max_length=60, verbose_name='Name field text'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='phone_placeholder',
            field=models.CharField(default='Phone', max_length=60, verbose_name='Phone field text'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='subheading',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sub-heading'),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='description',
            field=models.CharField(default='Share a few details and our team will get back within one working day.', max_length=255, verbose_name='Response line'),
        ),
        migrations.CreateModel(
            name='EnquiryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('name', models.CharField(max_length=100, verbose_name='Service')),
                ('contact', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.contactsection')),
            ],
            options={
                'verbose_name': 'Dropdown option',
                'verbose_name_plural': 'Service dropdown options',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.faqsection')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
